version: '3.1'
services:
  app:
    container_name: api-desafio-insight
    image: api-desafio-insight
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=insight200!
      - POSTGRES_USER=insight
      - POSTGRES_DB=insightdb
